# Generated by Django 5.0 on 2023-12-11 17:46

import django.db.models.deletion
import utils.image_uploaders
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.image_uploaders.product_image_upload, verbose_name='Изображение'),
        ),
        migrations.CreateModel(
            name='AdditionalProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.image_uploaders.product_image_upload)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Дополнительная иллюстрация твоара',
                'verbose_name_plural': 'Дополнительные иллюстрации товара',
            },
        ),
    ]
