# Generated by Django 5.0 on 2023-12-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_image_additionalproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalproductimage',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
