# Generated by Django 5.0 on 2023-12-18 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_additionalproductimage_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='items_of_cart', to='main.cartitem', verbose_name='Товары'),
        ),
    ]
