# Generated by Django 5.0 on 2023-12-18 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, verbose_name='Общая стоимость'),
        ),
    ]
