# Generated by Django 5.0 on 2023-12-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_cart_total_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Общая стоимость'),
        ),
    ]
