# Generated by Django 5.0 on 2023-12-11 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchFilterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('checkbox', 'чекбокс'), ('radiobutton', 'радиокнопка')], default='checkbox', max_length=64, verbose_name='Ключ поиска')),
                ('html_code', models.TextField(verbose_name='HTML-код страницы фильтрации')),
            ],
            options={
                'verbose_name': 'Тип поиска при фильтрации',
                'verbose_name_plural': 'Типы поиска при фильрации',
            },
        ),
        migrations.CreateModel(
            name='SpecCategoryName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Название характеристики')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ характеристики')),
                ('use_in_produt_shortlist_specs', models.BooleanField(default=False, verbose_name='Используется для отображения в описании твоара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория')),
                ('search_filter_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.searchfiltertype', verbose_name='Тип фильтра для поиска')),
            ],
            options={
                'verbose_name': 'Категория характеристик',
                'verbose_name_plural': 'Категории характеристик',
                'unique_together': {('category', 'name', 'key')},
            },
        ),
        migrations.CreateModel(
            name='SpecUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование величины')),
                ('unit', models.CharField(max_length=16, verbose_name='Единица измерения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Категория характеристики')),
            ],
            options={
                'verbose_name': 'Единица измерения характеристики',
                'verbose_name_plural': 'Еденицы измерения характеристик',
                'unique_together': {('category', 'name', 'unit')},
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64, verbose_name='Значение характеристики')),
                ('var_type', models.CharField(blank=True, choices=[('int', 'Целое число'), ('str', 'Стррока'), ('float', 'Число с плавающей точкой'), ('bool', 'Логический тип')], max_length=32, null=True, verbose_name='Тип значения')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_specs', to='main.category', verbose_name='Категория характеристик')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_specs', to='main.product', verbose_name='Товар')),
                ('spec_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specnames', to='specs.speccategoryname', verbose_name='Наименование категории характеристики')),
                ('spec_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='specs.specunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Характеристика товара',
                'verbose_name_plural': 'Характеристики товаров',
                'unique_together': {('category', 'spec_category', 'product', 'value')},
            },
        ),
        migrations.CreateModel(
            name='SpecUnitValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование величины')),
                ('var_type', models.CharField(choices=[('int', 'Целое число'), ('str', 'Стррока'), ('float', 'Число с плавающей точкой'), ('bool', 'Логический тип')], max_length=32, verbose_name='Тип величины характеристики')),
                ('specunit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='specs.specunit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единицы измерения при валидации',
                'verbose_name_plural': 'Единицы измерения при валидации',
                'unique_together': {('specunit', 'name', 'var_type')},
            },
        ),
    ]
