# Generated by Django 5.0 on 2023-12-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('specs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='var_type',
            field=models.CharField(blank=True, choices=[('int', 'Целое число'), ('str', 'Строка'), ('float', 'Число с плавающей точкой'), ('bool', 'Логический тип')], max_length=32, null=True, verbose_name='Тип значения'),
        ),
    ]
